// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as App$RescriptReactSnowpackTestTailwind from "./App.bs.js";

var root = document.querySelector("#root");

if (root == null) {
  console.log("Missing #root element");
} else {
  ReactDom.render(React.createElement(App$RescriptReactSnowpackTestTailwind.make, {}), root);
}

export {
  
}
/* root Not a pure module */
